package pkg

// LoginUrl and BaseUrl can be overridden at build time via -ldflags
var (
	LoginUrl = "https://panel.virakcloud.com/web-service/create?name=cli-token-%s&abilities=*"
	BaseUrl  = "https://public-api.virakcloud.com"
)

const (
	ZoneList               string = "%s/zones"
	ZoneActiveServicesList string = "%s/zone/%s"
	ZoneNetworkList        string = "%s/zone/%s/network"
	ZoneResourcesList      string = "%s/zone/%s/resources"

	BucketList       string = "%s/zone/%s/object-storage/buckets"
	BucketCreate     string = "%s/zone/%s/object-storage/buckets"
	BucketShow       string = "%s/zone/%s/object-storage/buckets/%s"
	BucketUpdate     string = "%s/zone/%s/object-storage/buckets/%s"
	BucketDelete     string = "%s/zone/%s/object-storage/buckets/%s"
	BucketsEventList string = "%s/zone/%s/object-storage/events"
	BucketEventList  string = "%s/zone/%s/object-storage/buckets/%s/events"

	DomainListURL   string = "%s/dns/domains"
	DomainCreateURL string = "%s/dns/domains"
	DomainShowURL   string = "%s/dns/domains/%s"
	DomainDeleteURL string = "%s/dns/domains/%s"

	DNSEventsURL string = "%s/dns/events"

	RecordListURL   string = "%s/dns/domains/%s/records"
	RecordCreateURL string = "%s/dns/domains/%s/records"
	RecordUpdateURL string = "%s/dns/domains/%s/records/%s/%s/%s"
	RecordDeleteURL string = "%s/dns/domains/%s/records/%s/%s/%s"

	KubernetesClusterList          string = "%s/zone/%s/kubernetes"
	KubernetesClusterCreate        string = "%s/zone/%s/kubernetes"
	KubernetesClusterShow          string = "%s/zone/%s/kubernetes/%s"
	KubernetesClusterUpdate        string = "%s/zone/%s/kubernetes/%s"
	KubernetesClusterDelete        string = "%s/zone/%s/kubernetes/%s"
	KubernetesClusterStart         string = "%s/zone/%s/kubernetes/%s/start"
	KubernetesClusterStop          string = "%s/zone/%s/kubernetes/%s/stop"
	KubernetesClusterScale         string = "%s/zone/%s/kubernetes/%s/scale"
	KubernetesClusterEvents        string = "%s/zone/%s/kubernetes/%s/events"
	KubernetesServiceEvents        string = "%s/zone/%s/kubernetes/events"
	KubernetesVersionsList         string = "%s/zone/%s/kubernetes/versions"
	KubernetesServiceOfferingsList string = "%s/zone/%s/kubernetes/service-offerings"

	UserSSHKeyList       string = "%s/user/ssh-key"
	UserSSHKeyCreate     string = "%s/user/ssh-key"
	UserSSHKeyDelete     string = "%s/user/ssh-key/%s"
	UserBalance          string = "%s/user/finance/wallet"
	UserPaymentList      string = "%s/user/finance/payments"
	UserCostDocumentList string = "%s/user/finance/documents"
	UserTokenAbilities   string = "%s/user/token-abilities"
	UserTokenValidate    string = "%s/user/token"

	NetworkCreateL3           string = "%s/zone/%s/network/l3"
	NetworkCreateL2           string = "%s/zone/%s/network/l2"
	NetworkList               string = "%s/zone/%s/network"
	NetworkShow               string = "%s/zone/%s/network/%s"
	NetworkDelete             string = "%s/zone/%s/network/%s"
	NetworkInstanceConnect    string = "%s/zone/%s/network/%s/instance/connect"
	NetworkInstanceDisconnect string = "%s/zone/%s/network/%s/instance/disconnect"
	NetworkInstanceList       string = "%s/zone/%s/network/%s/instance"
	NetworkFirewallIPv4List   string = "%s/zone/%s/network/%s/firewall/ipv4"
	NetworkFirewallIPv4Create string = "%s/zone/%s/network/%s/firewall/ipv4"
	NetworkFirewallIPv4Delete string = "%s/zone/%s/network/%s/firewall/ipv4/%s"
	NetworkFirewallIPv6List   string = "%s/zone/%s/network/%s/firewall/ipv6"
	NetworkFirewallIPv6Create string = "%s/zone/%s/network/%s/firewall/ipv6"
	NetworkFirewallIPv6Delete string = "%s/zone/%s/network/%s/firewall/ipv6/%s"

	NetworkPublicIpList             string = "%s/zone/%s/network/%s/public-ip"
	NetworkPublicIpAssociate        string = "%s/zone/%s/network/%s/public-ip"
	NetworkPublicIpDisassociate     string = "%s/zone/%s/network/%s/public-ip/%s"
	NetworkPublicIpStaticNatEnable  string = "%s/zone/%s/network/%s/public-ip/%s/static-nat"
	NetworkPublicIpStaticNatDisable string = "%s/zone/%s/network/%s/public-ip/%s/static-nat"

	NetworkVpnShowURL    string = "%s/zone/%s/network/%s/vpn"
	NetworkVpnEnableURL  string = "%s/zone/%s/network/%s/vpn/enable"
	NetworkVpnDisableURL string = "%s/zone/%s/network/%s/vpn/disable"
	NetworkVpnUpdateURL  string = "%s/zone/%s/network/%s/vpn"

	NetworkLoadBalancerList         string = "%s/zone/%s/network/%s/load-balancer"
	NetworkLoadBalancerRuleCreate   string = "%s/zone/%s/network/%s/load-balancer/rule"
	NetworkLoadBalancerRuleDelete   string = "%s/zone/%s/network/%s/load-balancer/rule/%s"
	NetworkLoadBalancerRuleAssign   string = "%s/zone/%s/network/%s/load-balancer/rule/%s/assign"
	NetworkLoadBalancerRuleDeassign string = "%s/zone/%s/network/%s/load-balancer/rule/%s/de-assign"
	NetworkHaproxyLive              string = "%s/zone/%s/network/%s/ha/live"
	NetworkHaproxyLog               string = "%s/zone/%s/network/%s/ha/log"

	NetworkServiceOfferingList string = "%s/zone/%s/network/service-offering"

	InstanceList                string = "%s/zone/%s/instance"
	InstanceServiceOfferingList string = "%s/zone/%s/instance/service-offerings"
	InstanceVMImageList         string = "%s/zone/%s/instance/vm-images"
	InstanceCreate              string = "%s/zone/%s/instance"
	InstanceRebuild             string = "%s/zone/%s/instance/%s/rebuild"
	InstanceStart               string = "%s/zone/%s/instance/%s/start"
	InstanceStop                string = "%s/zone/%s/instance/%s/stop"
	InstanceReboot              string = "%s/zone/%s/instance/%s/reboot"
	InstanceDelete              string = "%s/zone/%s/instance/%s"
	InstanceShow                string = "%s/zone/%s/instance/%s"

	InstanceMetricsURL                   string = "%s/zone/%s/instance/%s/metrics"
	InstanceSnapshotCreateURL            string = "%s/zone/%s/instance/%s/snapshot"
	InstanceSnapshotDeleteURL            string = "%s/zone/%s/instance/%s/snapshot/%s"
	InstanceSnapshotRevertURL            string = "%s/zone/%s/instance/%s/snapshot/%s/revert"
	InstanceVolumeServiceOfferingListURL string = "%s/zone/%s/instance/volumes/service-offering"
	InstanceVolumeListURL                string = "%s/zone/%s/instance/volumes"
	InstanceVolumeCreateURL              string = "%s/zone/%s/instance/volumes"
	InstanceVolumeDeleteURL              string = "%s/zone/%s/instance/volumes/%s"
	InstanceVolumeDetachURL              string = "%s/zone/%s/instance/volumes/%s/detach/%s"
	InstanceVolumeAttachURL              string = "%s/zone/%s/instance/volumes/%s/attach/%s"
)
